eclipse/paho.mqtt-sn.embedded-c

README.md
Signed-off-by: James Sutton <james.sutton@uk.ibm.com>
=> Fixing urls in README.md

MQTTSNGateway/README.md, MQTTSNGateway/param.conf, MQTTSNGateway/src/MQTTSNGWBrokerRecvTask.cpp, MQTTSNGateway/src/MQTTSNGWBrokerRecvTask.h, MQTTSNGateway/src/MQTTSNGWDefines.h, MQTTSNGateway/src/MQTTSNGWProcess.cpp, MQTTSNGateway/src/MQTTSNGWProcess.h, MQTTSNGateway/src/MQTTSNGateway.cpp, MQTTSNGateway/src/MQTTSNGateway.h, MQTTSNGateway/src/linux/Network.cpp, MQTTSNGateway/src/linux/Network.h, MQTTSNGateway/src/linux/Threading.cpp, MQTTSNGateway/src/linux/Threading.h, Makefile
Add Documentation and sample of a configuration file.
Command line parameter specified the configuration file.
=> Update  #11, #12, #13  and BugFix of Network

MQTTSNGateway/param.conf, MQTTSNGateway/src/MQTTSNGWBrokerRecvTask.cpp, MQTTSNGateway/src/MQTTSNGWBrokerSendTask.cpp, MQTTSNGateway/src/MQTTSNGWClientRecvTask.cpp, MQTTSNGateway/src/MQTTSNGWClientSendTask.cpp, MQTTSNGateway/src/MQTTSNGWConnectionHandler.cpp, MQTTSNGateway/src/MQTTSNGWDefines.h, MQTTSNGateway/src/MQTTSNGWPacket.cpp, MQTTSNGateway/src/linux/udp/SensorNetwork.cpp, MQTTSNPacket/src/MQTTSNPacket.c
minimum packet length is 2. not 3.     
in ClientRecvTask.cpp  < 2 is invalid.   in MQTTSNGWPacket.cpp >1 is valid.    
in param.conf   PortNo 2000 is reserved for sisco.  change to 2001.
=> BugFix:   can't recive and send PINGREQ

MQTTSNGateway/src/MQTTSNGWBrokerSendTask.cpp
=> BugFix: stack smashing detected #23  LogPrint erro.

MQTTSNGateway/src/MQTTSNGWBrokerRecvTask.cpp, MQTTSNGateway/src/MQTTSNGWClient.cpp, MQTTSNGateway/src/MQTTSNGWClient.h, MQTTSNGateway/src/MQTTSNGWConnectionHandler.cpp, MQTTSNGateway/src/MQTTSNGWProcess.h, MQTTSNGateway/src/MQTTSNGateway.h, MQTTSNGateway/src/linux/Network.cpp, MQTTSNGateway/src/linux/xbee/SensorNetwork.cpp, MQTTSNGateway/src/tests/TestProcess.cpp, MQTTSNGateway/src/tests/TestQue.cpp, MQTTSNGateway/src/tests/TestTask.cpp, MQTTSNGateway/src/tests/TestTopicIdMap.cpp, MQTTSNGateway/src/tests/TestTopics.cpp, MQTTSNGateway/src/tests/TestTree23.cpp, MQTTSNGateway/src/tests/TestTree23.h, MQTTSNGateway/src/tests/mainTestProcess.cpp, Makefile
=> BugFix of Issue #41

MQTTSNGateway/src/MQTTSNGateway.h, MQTTSNGateway/src/linux/Network.cpp, MQTTSNGateway/src/linux/xbee/SensorNetwork.h
=> BugFix:  Issue #47  'START_BYTE' was not declared

.cproject, .travis.yml, MQTTSNGateway/Makefile, MQTTSNGateway/README.md, MQTTSNGateway/src/MQTTSNGWProcess.h, MQTTSNGateway/src/MQTTSNGWVersion.h, MQTTSNGateway/src/MQTTSNGWVersion.h.in, MQTTSNGateway/src/MQTTSNGateway.cpp, MQTTSNGateway/src/MQTTSNGateway.h
Change: Move a Makefile into MQTTSNGateway directory.
How to build
$ git clone -b gateway
https://github.com/eclipse/paho.mqtt-sn.embedded-c 
$ cd paho.mqtt-sn.embedded-c/MQTTSNGateway       
$ make   
$ make install   
$ make clean        
=> Update: Add Travis CI check.

.travis.yml, MQTTSNGateway/GatewayTester/samples/mainTemplate.cpp, MQTTSNGateway/GatewayTester/samples/mainTest.cpp, MQTTSNGateway/GatewayTester/src/LGwProxy.cpp, MQTTSNGateway/GatewayTester/src/LMqttsnClient.cpp, MQTTSNGateway/GatewayTester/src/LMqttsnClientApp.h, MQTTSNGateway/GatewayTester/src/LNetworkUdp.cpp, MQTTSNGateway/GatewayTester/src/LPublishManager.cpp, MQTTSNGateway/GatewayTester/src/LSubscribeManager.cpp, MQTTSNGateway/GatewayTester/src/LTaskManager.cpp, MQTTSNGateway/Makefile, MQTTSNGateway/src/MQTTSNGWProcess.h, MQTTSNGateway/src/tests/TestProcess.cpp, MQTTSNGateway/src/tests/TestTree23.cpp
GatewayTester is a MQTT-SN Client program for testing Gateway.
It is a terminal application which needs  Interactive response by keyboard inputs. 
So compilation only, it cannot run on the Travis CI.
=> Add GatewayTester program compilation scripts to .travis.yml file.

MQTTSNGateway/README.md
Line feeds are incorrect.
The background of the input lines are  incorrect.
=> Change README.md format nicely.

MQTTSNGateway/GatewayTester/samples/mainTest.cpp, MQTTSNGateway/src/linux/udp/SensorNetwork.cpp
This will help to implement a new SensorNetwork class.
=> Add comments to SensorNetwork source code

.travis.yml, MQTTSNGateway/src/linux/udp6/SensorNetwork.cpp, MQTTSNGateway/src/linux/udp6/SensorNetwork.h
Add Benjamin's UDP6 SensorNetwork programs.
=> Added specific interface to send UDP6 packets

MQTTSNGateway/src/linux/udp6/SensorNetwork.cpp
Signed-off-by: Benjamin Aigner <aignerb@technikum-wien.at>
=> Changed output from cout to WRITELOG

MQTTSNGateway/README.md, MQTTSNGateway/src/linux/xbee/SensorNetwork.cpp
Update the README according to the change of branch name.
=> Add    João Eduardo's contribution instead of him.

MQTTSNGateway/src/MQTTGWPacket.cpp, MQTTSNGateway/src/MQTTSNGWBrokerSendTask.cpp, MQTTSNGateway/src/linux/Network.cpp
=> BugFix: MQTT packets wiith no payload can't be received correctly.

MQTTSNClient/src/MQTTSNClient.h, MQTTSNPacket/src/MQTTSNPacket.c
Signed-off-by: seko24 <seb12@mailbox.org>
=> Fixing issue #72: Setting minimum message length to 2.

MQTTSNGateway/src/linux/udp6/SensorNetwork.cpp
Signed-off-by: Ciupis, Jedrzej <jedrzej.ciupis@nordicsemi.no>
I am running the Paho MQTT-SN Gateway on Thread. It's a protocol that natively uses UDP on IPv6. I have encountered a problem with IPv6 adresses scope in the gateway. There are 3 issues:
1. I need to send multicast MQTT-SN messages to all nodes in my Thread network, so multicast address scope greater than link-local (ff02::1) is necessary. Setting broadcast address in gateway config file to e.g. ff03::1 causes the gateway to stop sending multicast messages.
2. Thread devices are usually addressed with global unicast IPv6 addresses, so again link-local unicast address (fe80::/10) is insufficient in scope. Devices with global IPv6 addresses can't be reached by the gateway.
3. Apart from the scope issues, port number in unicast …
=> Fix IPv6 address scope bug

MQTTSNGateway/GatewayTester/samples/mainTest.cpp, MQTTSNGateway/GatewayTester/src/LGwProxy.cpp, MQTTSNGateway/GatewayTester/src/LGwProxy.h, MQTTSNGateway/GatewayTester/src/LMqttsnClient.cpp, MQTTSNGateway/GatewayTester/src/LMqttsnClient.h, MQTTSNGateway/GatewayTester/src/LNetworkUdp.cpp, MQTTSNGateway/GatewayTester/src/LPublishManager.cpp, MQTTSNGateway/GatewayTester/src/LScreen.cpp, MQTTSNGateway/GatewayTester/src/LSubscribeManager.cpp, MQTTSNGateway/GatewayTester/src/LTimer.cpp, MQTTSNGateway/GatewayTester/src/LTimer.h, MQTTSNGateway/src/MQTTGWConnectionHandler.cpp, MQTTSNGateway/src/MQTTGWPacket.cpp, MQTTSNGateway/src/MQTTGWPacket.h, MQTTSNGateway/src/MQTTGWPublishHandler.cpp, MQTTSNGateway/src/MQTTSNGWClient.cpp, MQTTSNGateway/src/MQTTSNGWClient.h, MQTTSNGateway/src/MQTTSNGWConnectionHandler.cpp, MQTTSNGateway/src/MQTTSNGWDefines.h, MQTTSNGateway/src/MQTTSNGWPublishHandler.cpp, MQTTSNGateway/src/linux/Timer.h, MQTTSNGateway/src/linux/udp/SensorNetwork.cpp, MQTTSNGateway/src/linux/udp6/SensorNetwork.cpp, MQTTSNGateway/src/linux/xbee/SensorNetwork.cpp
1.Return CONNACK instead of the broker when the gateway receives CONNECT
while the client is Sleep or Awake mode.
2.Define the max size of a que for PUBLISH while the client state is
Asleep mode.  Despose packets when the que is full of packets.
3.Return PUBACK or PUBREL to the broker when the client is Asleep or
Awake.
=> BugFix of #76 and #77

MQTTSNGateway/src/MQTTSNGWDefines.h
=> Update: forget to delete #define DEBUG

MQTTSNGateway/src/MQTTGWConnectionHandler.cpp, MQTTSNGateway/src/MQTTSNGWClientRecvTask.cpp, MQTTSNGateway/src/MQTTSNGWClientSendTask.cpp
1. sleepy node problem
2. sender of PINGREQ in the log
=> Bugfix of #80

MQTTSNGateway/README.md
=> Update Explanation of Multicast Address #83

MQTTSNGateway/Makefile, MQTTSNGateway/src/MQTTSNGWClient.cpp
=> Update make codes simple #86

MQTTSNGateway/src/MQTTGWPacket.cpp, MQTTSNGateway/src/MQTTSNGWPacketHandleTask.cpp, MQTTSNGateway/src/MQTTSNGWPublishHandler.cpp, MQTTSNGateway/src/MQTTSNGWPublishHandler.h
=> Bugfix of #91, #93

MQTTSNGateway/src/MQTTGWPublishHandler.cpp
=> BugFix of #93

MQTTSNGateway/src/MQTTGWPublishHandler.cpp, MQTTSNGateway/src/MQTTSNGWClient.cpp, MQTTSNGateway/src/MQTTSNGWClient.h, MQTTSNGateway/src/MQTTSNGWPacketHandleTask.cpp, MQTTSNGateway/src/MQTTSNGWPublishHandler.cpp, MQTTSNGateway/src/MQTTSNGWSubscribeHandler.cpp
Hi,
Here are some improvements for MQTTGateway.  I hope you will find them useful.
=> Gateway improvements

MQTTSNGateway/src/MQTTSNGWClient.cpp, MQTTSNGateway/src/tests/TestTopics.cpp
Hi,
This should improve matching topics. New tests were also added. Please review.
Signed-off-by: Mariusz <mariusz.suchora@tieto.com>
=> BugFix of #105

.cproject, MQTTSNGateway/GatewayTester/Makefile, MQTTSNGateway/GatewayTester/samples/ClientPub/mainPub.cpp, MQTTSNGateway/GatewayTester/samples/ClientSub/mainSub.cpp, MQTTSNGateway/GatewayTester/src/LGwProxy.cpp, MQTTSNGateway/GatewayTester/src/LGwProxy.h, MQTTSNGateway/GatewayTester/src/LMqttsnClient.cpp, MQTTSNGateway/GatewayTester/src/LMqttsnClient.h, MQTTSNGateway/GatewayTester/src/LMqttsnClientApp.h, MQTTSNGateway/GatewayTester/src/LPublishManager.cpp, MQTTSNGateway/src/MQTTSNGWClientRecvTask.cpp, MQTTSNGateway/src/MQTTSNGWClientSendTask.cpp, MQTTSNGateway/src/MQTTSNGWConnectionHandler.cpp
Add two programs to test the non-clean session.
one is MQTT-SNPub and the other is MQTT-SNSub.
=> Add two test programs.

.cproject, MQTTSNGateway/GatewayTester/samples/mainTest.cpp, MQTTSNGateway/README.md, MQTTSNGateway/clients.conf, MQTTSNGateway/gateway.conf, MQTTSNGateway/src/MQTTSNGWClientList.cpp, MQTTSNGateway/src/MQTTSNGWClientSendTask.cpp, MQTTSNGateway/src/MQTTSNGWLogmonitor.cpp, MQTTSNGateway/src/MQTTSNGWSubscribeHandler.cpp, MQTTSNGateway/src/linux/udp6/SensorNetwork.cpp, MQTTSNGateway/src/tests/TestProcess.cpp
=> BugFix of #149 and #151

MQTTSNGateway/src/MQTTGWPublishHandler.cpp
Revert a line deleted by commit 15c527e
=> Bugfix of  #246
